# Generated by Django 6.0.3 on 2026-03-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasDoc',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
                'db_table': 'categorias_doc',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='UserProfe',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('correo_profe', models.EmailField(max_length=254, unique=True)),
                ('password_profe', models.CharField(max_length=60)),
                ('numero_profe', models.IntegerField(blank=True, null=True)),
                ('genero_profe', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('ND', 'Prefiero no decir')], max_length=2, null=True)),
                ('rol_profe', models.CharField(choices=[('INVESTIGADOR', 'Investigador'), ('MEDIO_TIEMPO', 'Profesor Medio Tiempo'), ('TIEMPO_COMPLETO', 'Profesor Tiempo Completo')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'user_profe',
                'ordering': ['correo_profe'],
            },
        ),
        migrations.CreateModel(
            name='InfCarpeta',
            fields=[
                ('id_folder', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carpeta', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='api.infcarpeta')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='api.userprofe')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'db_table': 'inf_carpeta',
                'unique_together': {('id_profesor', 'nombre_carpeta', 'id_padre')},
            },
        ),
        migrations.CreateModel(
            name='InfCurp',
            fields=[
                ('id_curp', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curp_info', to='api.userprofe')),
            ],
            options={
                'verbose_name': 'Información CURP',
                'verbose_name_plural': 'Información CURP',
                'db_table': 'inf_curp',
            },
        ),
        migrations.CreateModel(
            name='DocExpediente',
            fields=[
                ('id_exp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_convocatoria', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expedicion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='api.userprofe')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'doc_expediente',
                'unique_together': {('id_profesor', 'nombre_convocatoria')},
            },
        ),
        migrations.CreateModel(
            name='DocDocumento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_doc', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expedicion', models.DateTimeField(blank=True, null=True)),
                ('ruta_archivo', models.TextField()),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='api.categoriasdoc')),
                ('id_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='api.infcarpeta')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.userprofe')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'doc_documento',
                'unique_together': {('id_profesor', 'titulo_doc')},
            },
        ),
        migrations.CreateModel(
            name='ExpedienteContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.docdocumento')),
                ('id_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.docexpediente')),
            ],
            options={
                'verbose_name': 'Contenido de Expediente',
                'verbose_name_plural': 'Contenidos de Expedientes',
                'db_table': 'expediente_contenido',
                'ordering': ['orden'],
                'unique_together': {('id_exp', 'id_doc')},
            },
        ),
        migrations.CreateModel(
            name='VersionDoc',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('num_version', models.IntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='api.docdocumento')),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'db_table': 'version_doc',
                'ordering': ['-num_version'],
                'unique_together': {('id_doc', 'num_version')},
            },
        ),
    ]
