# Generated by Django 6.0.3 on 2026-05-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasDoc',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
                'db_table': 'categorias_doc',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.CreateModel(
            name='DocExpediente',
            fields=[
                ('id_exp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_convocatoria', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expedicion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='usuarios_backend.userprofe')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'doc_expediente',
                'unique_together': {('id_profesor', 'nombre_convocatoria')},
            },
        ),
        migrations.CreateModel(
            name='InfCarpeta',
            fields=[
                ('id_folder', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carpeta', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_padre', models.ForeignKey(blank=True, db_column='id_padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='gestion_expedientes_backend.infcarpeta')),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='usuarios_backend.userprofe')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'db_table': 'inf_carpeta',
                'unique_together': {('id_profesor', 'nombre_carpeta', 'id_padre')},
            },
        ),
        migrations.CreateModel(
            name='DocDocumento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_doc', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expedicion', models.DateTimeField(blank=True, null=True)),
                ('ruta_archivo', models.TextField()),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('extension_archivo', models.CharField(blank=True, default='', max_length=10)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios_backend.userprofe')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='gestion_expedientes_backend.categoriasdoc')),
                ('id_folder', models.ForeignKey(blank=True, db_column='id_folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='gestion_expedientes_backend.infcarpeta')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'doc_documento',
                'unique_together': {('id_profesor', 'titulo_doc')},
            },
        ),
        migrations.CreateModel(
            name='ExpedienteContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_doc', models.ForeignKey(db_column='id_doc', on_delete=django.db.models.deletion.CASCADE, to='gestion_expedientes_backend.docdocumento')),
                ('id_exp', models.ForeignKey(db_column='id_exp', on_delete=django.db.models.deletion.CASCADE, to='gestion_expedientes_backend.docexpediente')),
            ],
            options={
                'verbose_name': 'Contenido de Expediente',
                'verbose_name_plural': 'Contenidos de Expedientes',
                'db_table': 'expediente_contenido',
                'ordering': ['orden'],
                'unique_together': {('id_exp', 'id_doc')},
            },
        ),
        migrations.CreateModel(
            name='VersionDoc',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('num_version', models.IntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_doc', models.ForeignKey(db_column='id_doc', on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='gestion_expedientes_backend.docdocumento')),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'db_table': 'version_doc',
                'ordering': ['-num_version'],
                'unique_together': {('id_doc', 'num_version')},
            },
        ),
    ]
