# Generated by Django 6.0.3 on 2026-05-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_expedientes_backend', '0001_initial'),
        ('usuarios_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCustom',
            fields=[
                ('id_cat_custom', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('campos', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='categorias_custom', to='usuarios_backend.userprofe')),
            ],
            options={
                'verbose_name': 'Categoría Personalizada',
                'verbose_name_plural': 'Categorías Personalizadas',
                'db_table': 'categoria_custom',
                'ordering': ['nombre'],
                'unique_together': {('id_profesor', 'nombre')},
            },
        ),
    ]
