# Generated by Django 6.0.3 on 2026-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfe',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('correo_profe', models.EmailField(max_length=254, unique=True)),
                ('password_profe', models.CharField(max_length=60)),
                ('numero_profe', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'user_profe',
                'ordering': ['correo_profe'],
            },
        ),
    ]
