# Generated by Django 6.0.3 on 2026-05-18 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigadorID',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='investigador_ids', to='usuarios_backend.userprofe')),
            ],
            options={
                'verbose_name': 'ID de Investigador',
                'verbose_name_plural': 'IDs de Investigador',
                'db_table': 'investigador_id',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
