# Generated by Django 6.0.3 on 2026-05-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofe',
            name='curp',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='empresa',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='nivel_estudios',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='profesion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='puesto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='rfc',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofe',
            name='universidad',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
