# Generated by Django 6.0.3 on 2026-05-20 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_backend', '0002_add_profile_extended_fields'),
        ('usuarios_backend', '0002_investigadorid'),
    ]

    operations = [
    ]
